### PR TITLE
Trap exit signals and exit gracefully

### PR DESCRIPTION
**Pull request by majorz**
Change-Type: patch
Connects-To: #180
---- Autogenerated Waffleboard Connection: Connects to #180

### CODE REVIEW

**Comment by majorz** [comment]
A new thread is spawned for trapping Unix exit signals. The main thread is masked to not receive them, which is inherited by all child threads as well. If Crtl+C is pressed or the application is killed with SIGTERM, the signal handling thread will trap those signals and the application will shutdown gracefully by stopping the access point and exiting the dnsmasq child process.

**Comment by dhoney** [comment]
@majorz Is it just Ctrl-C or will any SIGTERM get caught and end the processes and child ones?

I used `kill PID` which sends SIGTERM but I still see dnsmasq up, am I using this correctly?

*steps to reproduce*
1. Found PID of `wifi-connect`  
```
root@fc01e9c:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
/usr/src/app/scripts/blink_monitor.sh
root       193  0.2  0.3   4252  3420 ?        Ss   19:33   0:10 /usr/local/sbin/openvpn --config /data/openvpn.conf
root       195  1.4  1.1  14156 11948 ?        Ss   19:33   1:05 /usr/bin/python /usr/src/app/common/netsvc.py
root       196  0.3  0.2  31784  2876 ?        Ssl  19:33   0:17 /usr/local/bin/redis-server 127.0.0.1:6379
message+   199  0.0  0.2   4688  2372 ?        Ss   19:33   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activatio
dirmngr    232  0.0  0.1   2884  1364 ?        Ss   19:33   0:01 /usr/bin/dirmngr --daemon --sh
root       322  0.0  0.2   2984  2248 ?        Ss   19:34   0:00 /bin/bash /usr/src/app/scripts/config_puller.sh
root      2201  0.4  0.8  11408  8816 ?        Ss   19:37   0:20 /usr/bin/python /usr/src/app/machines/main.py
root     20271  0.0  0.7   9420  7208 ?        Ss   20:34   0:00 /usr/bin/python3 /usr/src/app/scripts/ntpcheck.py
root     20284  0.0  0.0      0     0 ?        Z    20:34   0:00 [hwclock] <defunct>
root     22529  0.0  0.0   1444   968 pts/1    S    20:40   0:00 /bin/sh scripts/wifi_check.sh
nobody   22566  0.0  0.2   5416  2272 pts/1    S    20:40   0:00 dnsmasq --address=/#/192.168.42.1 --dhcp-range=192.168.42.2,192.168.42.254 --dhcp-option=
root     25712  0.0  0.2 111596  2456 pts/1    Sl   20:48   0:00 /usr/src/app/wifi_ap_mode/wifi-connect -i wlan1 -s oden-device-7e7d -p oden7e7d -u /usr/s
root     25737  0.6  0.0      0     0 pts/1    Z    20:48   0:00 [dnsmasq] <defunct>
root     25984  0.0  0.0   1376   360 ?        S    20:49   0:00 sleep 100
root     26200 46.8  2.0  23232 20984 ?        Ss   20:49   0:02 /usr/bin/python /usr/src/app/scripts/monitoring.py
root     26226  0.0  0.0   1376   348 ?        S    20:49   0:00 sleep 2
root     26227  0.0  0.1   4324  1580 pts/1    R+   20:49   0:00 ps aux

2. kill process  
root@fc01e9c:/usr/src/app# kill 25712
root@fc01e9c:/usr/src/app# Terminated

3. verify dnsmasq and wifi-connect are stopped  
root@fc01e9c:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.3  23444  3544 ?        Ss   19:33   0:04 /sbin/init quiet systemd.show_status=0
root        31  0.0  0.0   3068   340 ?        S    19:33   0:00 sleep infinity
root        46  0.1  0.4   9536  4908 ?        Ss   19:33   0:08 /lib/systemd/systemd-journald
root        54  0.0  0.2  10568  2252 ?        Ss   19:33   0:00 /lib/systemd/systemd-udevd
root       176  0.0  0.2   4620  2476 pts/1    Ss   19:33   0:00 /bin/bash
root       191  0.8  0.2   3292  2552 ?        Ss   19:33   0:37 /bin/bash /usr/src/app/scripts/blink_monitor.sh
root       193  0.2  0.3   4252  3420 ?        Ss   19:33   0:10 /usr/local/sbin/openvpn --config /data/openvpn.conf
root       195  1.4  1.1  14156 11948 ?        Ss   19:33   1:05 /usr/bin/python /usr/src/app/common/netsvc.py
root       196  0.3  0.2  31784  2876 ?        Ssl  19:33   0:17 /usr/local/bin/redis-server 127.0.0.1:6379
message+   199  0.0  0.2   4688  2372 ?        Ss   19:33   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activatio
dirmngr    232  0.0  0.1   2884  1364 ?        Ss   19:33   0:01 /usr/bin/dirmngr --daemon --sh
root       322  0.0  0.2   2984  2248 ?        Ss   19:34   0:00 /bin/bash /usr/src/app/scripts/config_puller.sh
root      2201  0.4  0.8  11408  8816 ?        Ss   19:37   0:20 /usr/bin/python /usr/src/app/machines/main.py
root     20271  0.0  0.7   9420  7208 ?        Ss   20:34   0:00 /usr/bin/python3 /usr/src/app/scripts/ntpcheck.py
root     20284  0.0  0.0      0     0 ?        Z    20:34   0:00 [hwclock] <defunct>
root     22529  0.0  0.0   1444   968 pts/1    S    20:40   0:00 /bin/sh scripts/wifi_check.sh
nobody   22566  0.0  0.2   5416  2272 pts/1    S    20:40   0:00 dnsmasq --address=/#/192.168.42.1 --dhcp-range=192.168.42.2,192.168.42.254 --dhcp-option=
root     25984  0.0  0.0   1376   360 ?        S    20:49   0:00 sleep 100
root     26278  0.0  0.0   3068   344 pts/1    S    20:50   0:00 sleep 120
root     26334 29.3  2.0  23232 20928 ?        Ss   20:50   0:02 /usr/bin/python /usr/src/app/scripts/monitoring.py
root     26382  0.0  0.0   1376   328 ?        S    20:50   0:00 sleep 2
root     26383  0.0  0.1   4324  1708 pts/1    R+   20:50   0:00 ps aux

**Comment by majorz** [comment]
SIGTERM is trapped as well. I will do some local tests now and report back shortly.

**Comment by majorz** [comment]
No problems here. I am starting it with a minimal Dockerfile and start.sh on a RPi3 with a debian container and I am able to kill it gracefully when from a web terminal (to the conitainer). Can you please verify that it is 4.0.6 that is running on your side. If so, let's see what differences do you have with the minimal setup I have here.

**Comment by majorz** [comment]
It says:
```
Received SIGTERM
Exiting...
Stopping access point 'WiFi Connect'...
Access point 'WiFi Connect' stopped
```
Also are you able to kill it with Ctrl+C when you run it from the terminal directly?

**Pull request merged**
